import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthProvider";
import  ButtonLogout  from "@/components/ButtonLogout";
import Link from "next/link";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const Header = () => {
  return (
    <header className="bg-gray-700 text-white py-4">
      <div className="container mx-auto">
        <nav className="flex justify-between items-center">
          <div className="flex gap-5 items-center">
            <Link
              className="text-white hover:text-gray-300 transition-colors duration-300 cursor-pointer"
              href="/"
            >
              Página Inicial
            </Link>
            <Link
              className="text-white hover:text-gray-300 transition-colors duration-300 cursor-pointer"
              href="/metas"
            >
              Metas
            </Link>
            <Link
              className="text-white hover:text-gray-300 transition-colors duration-300 cursor-pointer"
              href="/novaMeta"
            >
              Nova Meta
            </Link>
          </div>
          <div>
            <ButtonLogout />
          </div>
        </nav>
      </div>
    </header>
  );
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Header />
          {children}
          </AuthContextProvider>
        </body>
    </html>
  );
}
